{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "healthcare-prediction-api.fullname" . }}-config
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "healthcare-prediction-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: configuration
data:
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}